name: Common CI

on:
  workflow_call:
    inputs:
      message:
        description: "Message to echo"
        required: true
        type: string

jobs:
  simple-task:
    runs-on: ubuntu-latest

    steps:
      - name: Echo message1
        run: |
          echo "Message from input: ${{ inputs.message }}"
      - name: Echo message2
        run: |
          echo "Message from input: ${{ inputs.message }}"
